# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 81ee3addf95d14f629c5929d00c14ab21799c30f565f45aa47e59ab0d3e14a942349e4a18057fea576eedf3a6427a13ae37ac7caf2181b4650653d67eda66ac2

test:
  secret_key_base: ab8580416220fcc2a27c29f278069a11b473ac6adcfb2be67cb6503a5bc7699e524b337237198ed4c1310973ce71d738b90eb26cf876f267a8f063a41e6a2581

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
